server:
  port: 8080
spring:
  datasource:
    name: gridmanage
    url: jdbc:mysql://localhost:3306/unionlibrary?serverTimezone=GMT%2B8
    username: root
    password: ad5226236
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  #  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.library.entity
mapper:
  style: normal
logging:
  level:
    root: debug