server:
  port: 8080
spring:
  datasource:
    name: gridmanage
    url: jdbc:mysql://localhost:3306/unionlibrary?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ad5226236
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  设置时区没有生效，这里改jackson的设置
  jackson:
    time-zone: GMT+8
mybatis:
  #  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.library.entity
mapper:
  style: normal
logging:
  level:
    root: debug